language: node_js
dist: trusty
node_js:
- node
- '8'
install:
- npm install
script:
- npm run lint
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_d9c253c28478_key -iv $encrypted_d9c253c28478_iv
  -in config.js.enc -out config.js -d
- openssl aes-256-cbc -K $encrypted_4e211390bfca_key -iv $encrypted_4e211390bfca_iv
  -in test/config.js.enc -out test/config.js -d
